### ISSUE TITLE
`python sst.py` got an error

### ISSUE THREAD

**Issue by zhou1xiang2** [Eric-Wallace/universal-triggers#1]
Traceback (most recent call last):
  File "sst.py", line 184, in <module>
    main()
  File "sst.py", line 155, in main
    averaged_grad = utils.get_average_grad(model, batch, trigger_token_ids)
  File "../utils.py", line 84, in get_average_grad
    loss.backward()
  File "/anaconda3/envs/triggers/lib/python3.6/site-packages/torch/tensor.py", line 102, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/anaconda3/envs/triggers/lib/python3.6/site-packages/torch/autograd/__init__.py", line 90, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: cudnn RNN backward can only be called in training mode

**Comment by Eric-Wallace** [comment]
Hi, sorry I pushed some slight out-of-date code. Could you pull the latest and the error should go away.

**Comment by zhou1xiang2** [comment]
Thanks, it works
