### ISSUE TITLE
python create_adv_token.py got an error 

### ISSUE THREAD

**Issue by cstfei** [Eric-Wallace/universal-triggers#19]
Traceback (most recent call last):
  File "/universal-triggers/gpt2/create_adv_token.py", line 10, in <module>
    import utils
  File "/universal-triggers/gpt2/utils.py", line 8, in <module>
    from allennlp.data.iterators import BucketIterator
  File "/usr/local/lib/python3.8/dist-packages/allennlp/data/__init__.py", line 1, in <module>
    from allennlp.data.dataset_readers.dataset_reader import DatasetReader
  File "/usr/local/lib/python3.8/dist-packages/allennlp/data/dataset_readers/__init__.py", line 10, in <module>
    from allennlp.data.dataset_readers.ccgbank import CcgBankDatasetReader
  File "/usr/local/lib/python3.8/dist-packages/allennlp/data/dataset_readers/ccgbank.py", line 9, in <module>
    from allennlp.data.dataset_readers.dataset_reader import DatasetReader
  File "/usr/local/lib/python3.8/dist-packages/allennlp/data/dataset_readers/dataset_reader.py", line 8, in <module>
    from allennlp.data.instance import Instance
  File "/usr/local/lib/python3.8/dist-packages/allennlp/data/instance.py", line 3, in <module>
    from allennlp.data.fields.field import DataArray, Field
  File "/usr/local/lib/python3.8/dist-packages/allennlp/data/fields/__init__.py", line 7, in <module>
    from allennlp.data.fields.array_field import ArrayField
  File "/usr/local/lib/python3.8/dist-packages/allennlp/data/fields/array_field.py", line 10, in <module>
    class ArrayField(Field[numpy.ndarray]):
  File "/usr/local/lib/python3.8/dist-packages/allennlp/data/fields/array_field.py", line 51, in ArrayField
    def empty_field(self):  # pylint: disable=no-self-use
  File "/usr/local/lib/python3.8/dist-packages/overrides/overrides.py", line 88, in overrides
    return _overrides(method, check_signature, check_at_runtime)
  File "/usr/local/lib/python3.8/dist-packages/overrides/overrides.py", line 114, in _overrides
    _validate_method(method, super_class, check_signature)
  File "/usr/local/lib/python3.8/dist-packages/overrides/overrides.py", line 135, in _validate_method
    ensure_signature_is_compatible(super_method, method, is_static)
  File "/usr/local/lib/python3.8/dist-packages/overrides/signature.py", line 93, in ensure_signature_is_compatible
    ensure_return_type_compatibility(super_type_hints, sub_type_hints, method_name)
  File "/usr/local/lib/python3.8/dist-packages/overrides/signature.py", line 287, in ensure_return_type_compatibility
    raise TypeError(
TypeError: ArrayField.empty_field: return type `None` is not a `<class 'allennlp.data.fields.field.Field'>`.

**Comment by someshsingh22** [comment]
@cstfei Its due to the latest version of overrides on allennlp, downgrading overrides should work, try
```pip install overrides==3.1.0```

reference from https://github.com/allenai/allennlp/issues/5197#issuecomment-854675576
