### ISSUE TITLE
Error when running the squad script with up-to-date libraries

### ISSUE THREAD

**Issue by taylorshin** [Eric-Wallace/universal-triggers#8]
When I run `pip install -r requirements.txt` with the default requirements.txt file, I get the following error:
`Traceback (most recent call last):
  File "squad/squad.py", line 2, in <module>
    from allennlp.data.dataset_readers.reading_comprehension.squad import SquadReader
  File "/opt/conda/lib/python3.6/site-packages/allennlp/data/__init__.py", line 1, in <module>
    from allennlp.data.dataset_readers.dataset_reader import DatasetReader
  File "/opt/conda/lib/python3.6/site-packages/allennlp/data/dataset_readers/__init__.py", line 10, in <module>
    from allennlp.data.dataset_readers.ccgbank import CcgBankDatasetReader
  File "/opt/conda/lib/python3.6/site-packages/allennlp/data/dataset_readers/ccgbank.py", line 9, in <module>
    from allennlp.data.dataset_readers.dataset_reader import DatasetReader
  File "/opt/conda/lib/python3.6/site-packages/allennlp/data/dataset_readers/dataset_reader.py", line 8, in <module>
    from allennlp.data.instance import Instance
  File "/opt/conda/lib/python3.6/site-packages/allennlp/data/instance.py", line 3, in <module>
    from allennlp.data.fields.field import DataArray, Field
  File "/opt/conda/lib/python3.6/site-packages/allennlp/data/fields/__init__.py", line 10, in <module>
    from allennlp.data.fields.knowledge_graph_field import KnowledgeGraphField
  File "/opt/conda/lib/python3.6/site-packages/allennlp/data/fields/knowledge_graph_field.py", line 14, in <module>
    from allennlp.data.token_indexers.token_indexer import TokenIndexer, TokenType
  File "/opt/conda/lib/python3.6/site-packages/allennlp/data/token_indexers/__init__.py", line 5, in <module>
    from allennlp.data.token_indexers.dep_label_indexer import DepLabelIndexer
  File "/opt/conda/lib/python3.6/site-packages/allennlp/data/token_indexers/dep_label_indexer.py", line 9, in <module>
    from allennlp.data.tokenizers.token import Token
  File "/opt/conda/lib/python3.6/site-packages/allennlp/data/tokenizers/__init__.py", line 8, in <module>
    from allennlp.data.tokenizers.pretrained_transformer_tokenizer import PretrainedTransformerTokenizer
  File "/opt/conda/lib/python3.6/site-packages/allennlp/data/tokenizers/pretrained_transformer_tokenizer.py", line 5, in <module>
    from pytorch_transformers.tokenization_auto import AutoTokenizer
ModuleNotFoundError: No module named 'pytorch_transformers.tokenization_auto'`

So I install the latest version of allennlp with `pip install allennlp --upgrade` and get the following versions:
allennlp-0.9.0
pytorch-transformers-1.1.0

However, I still can't run the squad script because I get the following error:
`Traceback (most recent call last):
  File "squad.py", line 118, in <module>
    main()
  File "squad.py", line 19, in main
    model.eval().cuda()
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 265, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 193, in _apply
    module._apply(fn)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 193, in _apply
    module._apply(fn)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 127, in _apply
    self.flatten_parameters()
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 123, in flatten_parameters
    self.batch_first, bool(self.bidirectional))
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED`

I am running the code on an AWS instance with CUDA and Python 3.6.9. I would appreciate it if you could help me figure out what I'm doing wrong.

**Comment by Eric-Wallace** [comment]
Are you using anaconda? I recommend creating a brand new anaconda environment for this repository. 

Nevertheless, when you ran `pip install allennlp --upgrade`, I don't think this is what you wanted. The error was from pytorch_transformers, not allennlp.

In your current state, your allennlp and pytorch transformers libraries are too new. I recommend either using anaconda or uninstalling alennlp and pytorch transformers and reinstalling them.

**Comment by taylorshin** [comment]
I still get the first error when I create a brand new conda environment (with the default package versions) and it happens for snli, sst, and squad.

`Traceback (most recent call last):
  File "snli.py", line 3, in <module>
    from allennlp.data.dataset_readers.snli import SnliReader
  File "/opt/conda/envs/triggers/lib/python3.6/site-packages/allennlp/data/__init__.py", line 1, in <module>
    from allennlp.data.dataset_readers.dataset_reader import DatasetReader
  File "/opt/conda/envs/triggers/lib/python3.6/site-packages/allennlp/data/dataset_readers/__init__.py", line 10, in <module>
    from allennlp.data.dataset_readers.ccgbank import CcgBankDatasetReader
  File "/opt/conda/envs/triggers/lib/python3.6/site-packages/allennlp/data/dataset_readers/ccgbank.py", line 9, in <module>
    from allennlp.data.dataset_readers.dataset_reader import DatasetReader
  File "/opt/conda/envs/triggers/lib/python3.6/site-packages/allennlp/data/dataset_readers/dataset_reader.py", line 8, in <module>
    from allennlp.data.instance import Instance
  File "/opt/conda/envs/triggers/lib/python3.6/site-packages/allennlp/data/instance.py", line 3, in <module>
    from allennlp.data.fields.field import DataArray, Field
  File "/opt/conda/envs/triggers/lib/python3.6/site-packages/allennlp/data/fields/__init__.py", line 10, in <module>
    from allennlp.data.fields.knowledge_graph_field import KnowledgeGraphField
  File "/opt/conda/envs/triggers/lib/python3.6/site-packages/allennlp/data/fields/knowledge_graph_field.py", line 14, in <module>
    from allennlp.data.token_indexers.token_indexer import TokenIndexer, TokenType
  File "/opt/conda/envs/triggers/lib/python3.6/site-packages/allennlp/data/token_indexers/__init__.py", line 5, in <module>
    from allennlp.data.token_indexers.dep_label_indexer import DepLabelIndexer
  File "/opt/conda/envs/triggers/lib/python3.6/site-packages/allennlp/data/token_indexers/dep_label_indexer.py", line 9, in <module>
    from allennlp.data.tokenizers.token import Token
  File "/opt/conda/envs/triggers/lib/python3.6/site-packages/allennlp/data/tokenizers/__init__.py", line 8, in <module>
    from allennlp.data.tokenizers.pretrained_transformer_tokenizer import PretrainedTransformerTokenizer
  File "/opt/conda/envs/triggers/lib/python3.6/site-packages/allennlp/data/tokenizers/pretrained_transformer_tokenizer.py", line 5, in <module>
    from pytorch_transformers.tokenization_auto import AutoTokenizer
ModuleNotFoundError: No module named 'pytorch_transformers.tokenization_auto'`

**Comment by Eric-Wallace** [comment]
Hi, if you run `pip install pytorch_transformers==1.1`, it should fix the problem. It looks like the requirements for AllenNLP 0.85 changed somehow. I will update the requirements file.
